FROM eclipse-temurin:21-jdk AS builder
WORKDIR /app

# 멀티모듈 Gradle 빌드
COPY . .
RUN ./gradlew clean build -x test

FROM eclipse-temurin:21-jre
WORKDIR /app

ENV TZ=Asia/Seoul

COPY --from=builder /app/paylab-api/build/libs/paylab-api-*.jar paylab-api.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "paylab-api.jar"]